apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
        - name: java-kafka-consumer
          image: quay.io/mezzeddine/consumer24-1-2022:v1
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: TOPIC
              value: testtopic1
            - name: GROUP_ID
              value: testgroup1
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=100